---
title: "Forest Vegetation Plots QC"
author: "John Paul Schmit"
date: "5/18/2020"
output: html_document
---

```{r Plot_setup, include=F}

TotPlots<-nrow(QCPoints) #Total number of points being checked

# 1.1.0
Points_Bad_Unit<-QCPoints %>% 
   filter(!Admin_Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
   select(Admin_Unit_Code, Point_Name)
 
#1.2.0
Points_No_Point_Name<-QCPoints %>% 
    filter(is.na(Point_Name) | Point_Name=="") %>% 
    select(Admin_Unit_Code, Point_Name)
 
Points_Duplicated<-QCPoints %>% 
  group_by(Point_Name) %>% 
  summarize(Point_Count=n()) %>% 
  filter(Point_Count !=1) %>% 
  select(Point_Name, Point_Count)

# #1.3.0
# Plots_Bad_Slope_Aspect<-QCPlots %>% 
#    filter(Slope<0 | Slope >58 | is.na(Slope) | Aspect<=0 | Aspect >360 | (is.na(Aspect) & !Slope %in% 0)) %>% 
#    select(Unit_Code, Plot_Name, Slope, Aspect)
# 
# #1.4.0
# Plots_No_Coords<-QCPlots %>% 
#    filter(is.na(Latitude)| is.na(Longitude) | is.na(UTM_18N_NAD83_X) | is.na(UTM_18N_NAD83_Y)) %>% 
#    select(Unit_Code, Plot_Name, Latitude, Longitude, UTM_18N_NAD83_X, UTM_18N_NAD83_Y)
# 
# #1.5.0
# Plots_Bad_Coords<-QCPlots %>% 
#    filter(Latitude < 37.7| Latitude > 40.36|Longitude<  -79.5  | Longitude > -76.1 ) %>% 
#    select(Unit_Code, Plot_Name, Latitude, Longitude)
# 
# #1.6.0
# Plots_Bad_Panel <- QCPlots %>% 
#    filter(!Panel %in% 1:4) %>% 
#    select(Unit_Code, Plot_Name, Panel)
# 
# #1.7.0
# Plots_Bad_Frame<-QCPlots %>% 
#    filter(!Frame %in% c("Park", "Region")) %>% 
#    select(Unit_Code, Plot_Name, Frame)
# 
# #1.8.0
# Plots_Bad_GRTS<- QCPlots %>% 
#    filter(!GRTS_Order %in% 1:4683) %>% 
#    select(Unit_Code, Plot_Name, GRTS_Order)
# 
# Plots_Duplicated_GRTS<-QCPlots %>% 
#    group_by(GRTS_Order) %>% 
#    summarize(Plot_Count=n()) %>% 
#    filter(Plot_Count !=1) %>% 
#    pull(GRTS_Order) %>% 
#    {filter(QCPlots, GRTS_Order %in% .) %>% select(Unit_Code, Plot_Name, GRTS_Order)}
# 
# #1.9.0
# Plots_Bad_Location_Status<-QCPlots %>% 
#    filter(!Location_Status %in% c("Active", "Retired")) %>% 
#    select(Unit_Code, Plot_Name, Location_Status)
# 
# #1.10.0
# Plots_Bad_Event_Count<-QCPlots %>% 
#    filter(!Event_Count %in% 1:4) %>% 
#    select(Unit_Code, Plot_Name, Event_Count)
# 
# #1.11.0
# Plots_Bad_Event_Earliest<-QCPlots %>% 
#    filter(!year(Event_Earliest) %in% 2006:2017 | !month (Event_Earliest) %in% 5:10) %>% 
#    select(Unit_Code, Plot_Name, Event_Earliest)
# 
# #1.12.0
# Plots_Bad_Event_Latest<-QCPlots %>% 
#    filter(!year(Event_Latest) %in% 2007:2021 | !month (Event_Latest) %in% 4:10) %>% 
#    select(Unit_Code, Plot_Name, Event_Latest)
# 
# #1.13.0
# Plots_Bad_Install_Date<-QCPlots %>% 
#    filter(!year(Event_Latest) %in% 2007:2021 | !month (Event_Latest) %in% 4:10) %>% 
#    select(Unit_Code, Plot_Name, Event_Latest)
# 
# #1.13.0
# Plots_Bad_Install_Date<-QCPlots %>%
#    mutate(Install_Date2=mdy_hm(Install_Date)) %>% # currently the missing data makes R not parse this as Date
#    filter(!year(Install_Date2) %in% 2006:2017 | !month (Install_Date2) %in% 1:12) %>% 
#    select(Unit_Code, Plot_Name, Install_Date) # note - return original data, not the transformed data
# 
# #1.14.0
# Plots_Wrong_Order<-QCPlots %>% 
#    mutate(Install_Date2=mdy_hm(Install_Date)) %>% # currently the missing data makes R not parse this as Date
#    filter(Install_Date2 > Event_Latest | Install_Date2 > Event_Latest | Event_Earliest> Event_Latest) %>% 
#    select(Unit_Code, Plot_Name, Install_Date, Event_Earliest, Event_Latest)
# 
# #1.15.0 Reserved for Retired_Date
# 
# #1.16.0
# Plots_Bad_Jurisdiction<-QCPlots %>% 
#    filter(!(County=="District of Columbia" & State=="District of Columbia" & StateAbbrev=="DC") &
#           !(County %in% c("Allegany", "Anne Arundel", "Charles", "Frederick", "Montgomery","Prince George's", "Washington" ) & 
#                State=="Maryland" & StateAbbrev=="MD") & 
#          !(County %in% c("Alexandria", "Arlington", "Fairfax", "Loudoun", "Prince William", "Stafford") & State=="Virginia" & StateAbbrev=="VA") &
#             !(County=="Jefferson" & State=="West Virginia" & StateAbbrev=="WV")
#              ) %>% 
#    select(Unit_Code, Plot_Name, County, State, StateAbbrev)
# 
# #1.17.0
# Plots_Inconsistent_County<-QCPlots %>% 
#    filter(!(Unit_Code=="ANTI" & County =="Washington") &
#           !(Unit_Code=="CATO" & County =="Frederick") &
#           !(Unit_Code=="CHOH" & County %in% c("District of Columbia", "Montgomery","Frederick","Washington","Allegany")) &
#           !(Unit_Code=="GWMP" & County %in% c("District of Columbia", "Montgomery","Alexandria", "Arlington", "Fairfax")) &
#           !(Unit_Code=="HAFE" & County %in% c("Washington","Loudoun","Jefferson"))&
#           !(Unit_Code=="MANA" & County =="Prince William") &
#           !(Unit_Code=="MONO" & County =="Frederick") &
#           !(Unit_Code=="NACE" & County %in% c("District of Columbia","Anne Arundel", "Prince George's", "Charles")) &
#           !(Unit_Code=="PRWI" & County %in% c("Prince William","Stafford")) &
#           !(Unit_Code=="ROCR" & County =="District of Columbia") &
#           !(Unit_Code=="WOTR" & County =="Fairfax")
#           
#           ) %>% 
#    select(Unit_Code, Plot_Name, County, State, StateAbbrev)
# 
# 

```


#### **Plots Checked:** `r TotPlots` ####

### Unit Codes

```{r Point_unit_Codes, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Points_Bad_Unit)==0) cat("All points have a recognized Unit Code.<br>") else {
   errortext("Points with a missing or unrecongized Unit Code:"); NiceTable(Plots_Bad_Unit)}
```

---

### Plot Names

```{r Points_point_names, echo=FALSE, hold=FALSE, results="asis"}
if(nrow(Points_No_Point_Name)==0) cat("All points have a point name.<br>") else {
  errortext("Points without a point name:"); NiceTable(Points_No_Ponit_Name)}

if(nrow(Points_Duplicated)==0) cat("All points have a unique point name.<br>") else {
  errortext("Points with a duplicated point name:"); NiceTable(Points_Duplicated)}
```

---

### Slope and Aspect

```{r slope_aspect, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Slope and Aspect**<br>")
# if(nrow(Plots_Bad_Slope_Aspect)==0) cat("All plots have acceptable slope and aspect measurements.<br>") else {
#    errorText("Plots with a missing slope, missing aspect,  a slope <0 or >58, or an aspect <1 or >360"); NiceTable(Plots_Bad_Slope_Aspect)}
# 
```

---

### Geographic Coordinates

```{r geo_coords, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Coordinates Present**<br>")
# if(nrow(Plots_No_Coords)==0) cat("All plots have geographic coordinates.  \n") else { 
#    cat("Plots with missing coordinates:  \n"); NiceTable(Plots_No_Coords)}
# 
# cat("<br>**Bounding Box**<br>")
# if(nrow(Plots_Bad_Coords)==0) cat("All plots' latitude and longitude are within the NCRN bounding box.<br>") else {
#    errorText("Plots with lat/long outside bounding box:"); NiceTable(Plots_Bad_Coords)}
# 
# cat("<br>**Jursidiction**<br>")
# if(nrow(Plots_Bad_Jurisdiction)==0) cat("All plots' jurisdictions are consistent and within NCRN.<br>") else {
#    errorText("Plots with incorrect jurisdictions:"); NiceTable(Plots_Bad_Jurisdiction)}
# 
# cat("<br>**Counties and Parks**<br>")
# if(nrow(Plots_Inconsistent_County)==0) cat("All plots' counties are consistent with their park.<br>") else {
#    errorText("Plots with a mismatch between county and park:"); NiceTable(Plots_Inconsistent_County)}
# 
```

---

### Plot Sampling  Data

```{r plot_panel, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Panel**<br>")
# if(nrow(Plots_Bad_Panel)==0) cat("All plots have a Panel between 1 and 4.<br>") else {
#    errorText("Plots without a Panel between 1 and 4:"); NiceTable(Plots_Bad_Panel)}
# ```
# 
# ```{r plot_frame, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Frame**<br>")
# if(nrow(Plots_Bad_Frame)==0) cat("All plots have a frame of either Park or Region.<br>") else {
#    errorText("Plots without a frame of Park of Region:"); NiceTable(Plots_Bad_Frame)}
# ```
# 
# ```{r plot_bad_GRTS, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot GRTS Order**<br>")
# if(nrow(Plots_Bad_GRTS)==0) cat("All plots have a valid GRTS order.<br>") else {
#    errorText("Plots without a valid GRTS order:"); NiceTable(Plots_Bad_GRTS)}
# ```
# 
# ```{r plot_duplicated_GRTS, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plots with a duplicated GRTS order**<br>")
# if(nrow(Plots_Duplicated_GRTS)==0) cat("All plots have a unique GRTS order.<br>") else {
#    errorText("Plots with a duplicated GRTS order:"); NiceTable(Plots_Duplicated_GRTS)}
# ```
# 
# ```{r plot_location_status, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Location Status**<br>")
# if(nrow(Plots_Bad_Location_Status)==0) cat("All plots have a location status of Active or Retired.<br>") else {
#    errorText("Plots with a location status other that Active or Retired:"); NiceTable(Plots_Bad_Location_Status)}
```

---

### Plot Event Summaries

```{r plot_event_count, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Event Count**<br>")
# if(nrow(Plots_Bad_Event_Count)==0) cat("All plots have an Event Count between 1 and 4.<br>") else {
#    errorText("Plots without an Event Count between 1 and 4:"); NiceTable(Plots_Bad_Event_Count)}
# ```
# 
# ```{r plot_event_earliest, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Earliest Event**<br>")
# if(nrow(Plots_Bad_Event_Earliest)==0) cat("All plots have an earliest event between May and October and between 2006 to 2017.<br>") else {
#    errorText("Plots without an an earliest event between May and October and between 2006 to 2017:"); NiceTable(Plots_Bad_Event_Earliest)}
# ```
# 
# ```{r plot_event_latest, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Latest Event**<br>")
# if(nrow(Plots_Bad_Event_Latest)==0) cat("All plots have a latest event between April and October and between 2007 to 2021.<br>") else {
#    errorText("Plots without an a latest event between April and October and between 2007 to 2027:"); NiceTable(Plots_Bad_Event_Latest)}
# ```
# 
# ```{r plot_instal_date, echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Plot Install Date**<br>")
# if(nrow(Plots_Bad_Install_Date)==0) cat("All plots have an install date duing a valid month between 2006 to 2017.<br>") else {
#    errorText("Plots without an install date during a valid month between 2006 to 2017:"); NiceTable(Plots_Bad_Install_Date)}
#```

# ```{r plot_dates_wrong, echo=FALSE, hold=FALSE, results="asis"}
#cat("<br>**Plot Date Order**<br>")
# if(nrow(Plots_Wrong_Order)==0) cat("All plots have an install date before their first event which is before the latest event .<br>") else {
#    errorText("Plots whose install, first event and latest event dates are out of order:");   NiceTable(Plots_Wrong_Order)}
```
