---
title: "Forest Vegetation Events QC"
author: "John Paul Schmit"
date: "5/18/2020"
output: html_document
---

```{r Events_Setup, include=F}
TotVisits<-nrow(QCVisits) #Total Number of visits checked

# 2.1.0
Visits_Bad_Unit<-QCVisits %>% 
   filter(!Admin_Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
   select(Admin_Unit_Code, Point_Name)

#2.2.0
Visits_Missing_Point<-QCVisits %>% 
 filter(is.na(Point_Name) | Point_Name=="" | !Point_Name %in% QCPoints$Point_Name) %>% 
 select(Admin_Unit_Code, Point_Name, Year)
 
#2.3.0
Visits_No_Date<-QCVisits %>% left_join(QCPoints, by=c("Admin_Unit_Code","Point_Name")) %>%
 filter(is.na(EventDate) | EventDate=="")  %>%
 select(Admin_Unit_Code,Point_Name, Year, EventDate)

Visits_Date_Dupliacated<-QCVisits %>% 
  group_by(Admin_Unit_Code, Point_Name, Year, EventDate) %>% 
  summarise(Vists=n()) %>% 
  filter(Vists!=1)  %>%
  select(Admin_Unit_Code,Point_Name, Year, EventDate)

#2.4.0
Visits_Bad_Year<-QCVisits %>% filter(Year!=year(EventDate)) %>% 
   select(Admin_Unit_Code, Point_Name, EventDate, Year)
 
#2.5.0
Visits_Bad_StartTime<-QCVisits %>% 
  filter(is.na(StartTime) | StartTime=="" | !is.difftime(StartTime)) %>% 
  select(Admin_Unit_Code, Point_Name, EventDate, StartTime)

Visits_Bad_EndTime<-QCVisits %>% 
  filter(is.na(EndTime) | EndTime=="" | !is.difftime(EndTime)) %>% 
  select(Admin_Unit_Code, Point_Name, EventDate, EndTime)

Visits_Bad_Length <-QCVisits %>% 
  filter(EndTime- StartTime != 600) %>% 
  mutate(Length=EndTime - StartTime) %>% 
   select(Admin_Unit_Code, Point_Name, EventDate, StartTime, EndTime, Length)

#2.6.0
Visits_Bad_Visit<-QCVisits %>% 
  filter(!Visit %in% 1:3) %>% 
  select(Admin_Unit_Code, Point_Name, EventDate, Visit)




# #2.10.0
# Events_Duplicated<-QCEvents %>% 
#   group_by(Unit_Code, Plot_Name, Event_Date) %>% 
#   summarise(Event_Count=n()) %>% 
#   filter(Event_Count!=1)
# 
# #2.11.0
# Events_Bad_Panel<-QCEvents %>%
#   filter(!Panel %in% 1:4) %>% 
#   select(Unit_Code, Plot_Name,Event_Year, Panel)
# 
# #2.12.0
# Events_Bad_Frame<-QCEvents %>%
#   filter(!Frame %in% c("Park","Region")) %>% 
#   select(Unit_Code, Plot_Name,Event_Year, Frame)
# 
# #2.13.0
# Events_Bad_Cycle<-QCEvents %>% 
#   filter(!(Cycle==1 & Event_Year %in% 2005:2009) &
#          !(Cycle==2 & Event_Year %in% 2010:2013) &
#          !(Cycle==3 & Event_Year %in% 2014:2017) &
#          !(Cycle==4 & Event_Year %in% 2018:2022)) %>% 
#   select(Unit_Code,Plot_Name, Event_Year, Cycle)
# 
# #2.14.0
# Events_No_Pictures<-QCEvents %>% 
#   filter(!PicturesTaken %in% 1) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, PicturesTaken)
# 
# 
# #2.15.0
# Events_No_CWD<-QCEvents %>% 
#   filter( (!CWDCheck360 %in% 1) |
#           (!CWDCheck120 %in% 1) |
#           (!CWDCheck240 %in% 1)) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, CWDCheck360, CWDCheck240, CWDCheck120) %>% 
#   left_join( QCCWD %>% group_by(Plot_Name, Sample_Year, Transect_Azimuth) %>% summarise(CWD_Pieces=n()) %>%
#   pivot_wider(names_from = Transect_Azimuth, id_cols=c(Plot_Name, Sample_Year), values_from= CWD_Pieces, values_fill=0,
#               names_prefix="CWD_Pieces") %>% rename(Event_Year=Sample_Year)
#   )
# 
# #2.16.0
# Events_No_Invasive_Early_Detect<-QCEvents %>% 
#   filter(!InvasiveEarlyDetect %in% c(0,1)) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, InvasiveEarlyDetect)
# 
# #2.17.0
# Events_No_Rare_Species<-QCEvents %>% 
#   filter(!RareSpecies %in% c(0,1)) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, RareSpecies)
# 
# #2.18.0
# Events_No_Plot_Maint<-QCEvents %>% 
#   filter(!PlotMaintReqd %in% c(0,1)) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, PlotMaintReqd)
# 
# #2.19.0
# Events_Not_Verified<-QCEvents %>% 
#   filter(!Verified) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, Verified, Verified_Date)
# 
# #2.20.0
# Events_Bad_Verified_Date<-QCEvents %>% 
#   filter(Verified_Date!="" & is.na(as.Date(mdy_hms(Verified_Date)))) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, Verified, Verified_Date)
# 
# Events_Verified_Mismatch<-QCEvents %>% 
#   filter((Verified==0  & Verified_Date !="") | (Verified ==1 & is.na(as.Date(mdy_hms(Verified_Date))))) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, Verified, Verified_Date)
# 
# Events_Verified_Anachronism<-QCEvents %>% 
#   filter(Verified_Date!="", as.Date(mdy_hms(Verified_Date))<Event_Date) %>% 
#    select(Unit_Code, Plot_Name, Event_Year, Verified, Event_Date, Verified_Date)
# 
# #2.21.0
# 
# Events_Not_Certified<-QCEvents %>% 
#   filter(!Certified) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, Certified, Certified_Date)
# 
# Events_Certified_Not_Verified<-QCEvents %>% 
#   filter(Certified & !Verified) %>% 
#   select(Unit_Code, Plot_Name, Event_Year,Verified, Verified_Date, Certified, Certified_Date)
# 
# #2.22.0
#  Events_Bad_Certified_Date<-QCEvents %>% 
#    filter(Certified_Date!="" & is.na(as.Date(mdy_hms(Certified_Date)))) %>% 
#    select(Unit_Code, Plot_Name, Event_Year, Certified, Certified_Date)
#  
#  Events_Certified_Mismatch<-QCEvents %>% 
#   filter((Certified==0  & Certified_Date !="") | (Certified ==1 & is.na(as.Date(mdy_hms(Certified_Date))))) %>% 
#   select(Unit_Code, Plot_Name, Event_Year, Certified, Certified_Date)
#  
#  Events_Certified_Anachronism<-QCEvents %>% 
#   filter(Certified_Date!="", as.Date(mdy_hms(Certified_Date))<as.Date(mdy_hms(Verified_Date))) %>% 
#    select(Unit_Code, Plot_Name, Event_Year, Verified,Certified, Verified_Date, Certified_Date)
#  
# #2.23.0
#  
# Events_Bad_Data_Processing<-QCEvents %>% 
#   filter(!(DataProcessingLevelID==3 & DataProcessingLevelCode=="A" & DataProcessingLevel=="Accepted" & 
#              DataProcessingLevelDefn=="Data that have undergone all QA and QC procedures as defined in a published protocol and associated SOPs. Used in cases where a Quality Assurance Plan (QAP) has not been developed and approved.")  &
#            !(DataProcessingLevelID==1 & DataProcessingLevelCode=="R" & DataProcessingLevel=="Raw" & 
#              DataProcessingLevelDefn=="Data in their state of original collection, either in the form of paper or electronic field forms, electronic sensor files, or digital media (photo, video, or audio). These data generally have been collected following some QA procedures, but have not undergone any QC procedures.")
#            ) %>% 
#   select(Unit_Code,Plot_Name,Event_Year, DataProcessingLevelID, DataProcessingLevelCode, DataProcessingLevel, DataProcessingLevelDefn)
# 
# #2.24.0 
# Events_Data_Processing_Anachronism<-QCEvents %>% 
#   filter(DataProcessingLevelDate!="", as.Date(mdy_hms(DataProcessingLevelDate))<+as.Date(mdy_hms(Certified_Date))) %>% 
#    select(Unit_Code, Plot_Name, Event_Year, Certified, DataProcessingLevel, Certified_Date, DataProcessingLevelDate)

```

#### **Visits Checked:** `r TotVisits` ####


### Visits Unit Codes

```{r Visit_location, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Visits Unit Code**<br>")
if(nrow(Visits_Bad_Unit)==0) cat("All visits have a recoginized unit code.<br>") else {
errorText("Visits without a recognized unit code:"); NiceTable(Visits_Bad_Unit)}

```

---

### Visit Points

```{r Visit_Points, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing or Incorrect Point Name**<br>")
if(nrow(Visits_Missing_Point)==0) cat("All visits have a point name that we use.<br>") else {
errorText("Visits without a point name, or from a point we don't monitor:"); NiceTable(Visits_Missing_Point)}

```


---

### Visit Date

```{r Visit_Date, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Event Date**<br>")
if(nrow(Visits_No_Date)==0) cat("All visits have an event date.<br>") else {
errorText("Visits with no date:"); NiceTable(Visits_No_Date)}

cat("<br>**Mulitple Visits to a Point on the Same Day**<br>")
if(nrow(Visits_Date_Dupliacated)==0) cat("No point was visited more than once on a single day.<br>") else {
errorText("Points with more than one visits on a single day:"); NiceTable(Visits_Date_Dupliacated)}
 
cat("<br>**Year should match Visit Date**<br>")
if(nrow(Visits_Bad_Year)==0) cat("All visit years match their event dates.<br>") else {
errorText("There is a mismach between year and event date:"); NiceTable(Visits_Bad_Year)}

```

---

### Visit Time

```{r Visit_Time, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing or Incorrect Start Time**<br>")
if(nrow(Visits_Bad_StartTime)==0) cat("All visits have a start time.<br>") else {
errorText("Visits without a starting time:"); NiceTable(Visits_Bad_StartTime)}

cat("<br>**Missing or Incorrect End Time**<br>")
if(nrow(Visits_Bad_EndTime)==0) cat("All visits have an end time.<br>") else {
errorText("Visits without an ending time:"); NiceTable(Visits_Bad_EndTime)}

cat("<br>**Visits that lasted other than 10 minutes**<br>")
if(nrow(Visits_Bad_Length)==0) cat("All visits lasted 10 minutes.<br>") else {
errorText("Visits that were not 10 minutes long:"); NiceTable(Visits_Bad_Length)}

```

---

### Visit NUmber

```{r Visits_visit_mumber, echo=FALSE, hold=FALSE, results="asis"}
cat("<br>**Missing or Incorrect Visit Number**<br>")
if(nrow(Visits_Bad_Visit)==0) cat("All visits have a valid visit number.<br>") else {
errorText("Visits without a valid visit number:"); NiceTable(Visits_Bad_Visit)}

```




### Duplicated Events

```{r Event-Duped,echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Duplicated Event Data**<br>")
# if(nrow(Events_Duplicated)==0) cat("Each plot /date combination is unqiued.<br>") else {
# errorText("Plots with more than one event on the same day:"); NiceTable(Events_Duplicated)}

```

---

### Event Panel, Frame and Cycle

```{r Event_Panel_Frame_Cycle,echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Event Panel Data**<br>")
# if(nrow(Events_Bad_Panel)==0) cat("Each event has a panel code from 1 to 4.<br>") else {
# errorText("Events without a panel code from 1-4:"); NiceTable(Events_Bad_Panel)}
# 
# cat("<br>**Event Frame Data**<br>")
# if(nrow(Events_Bad_Frame)==0) cat("Each event has a frame that is either Region or Park.<br>") else {
# errorText("Events without a frame of either Region or Park:"); NiceTable(Events_Bad_Frame)}
# 
# cat("<br>**Event Cycle Data**<br>")
# if(nrow(Events_Bad_Cycle)==0) cat("Each event is from a cycle that matches its event year <br>") else {
# errorText("Events without a cycle or with a cycle that does not match its event year:"); NiceTable(Events_Bad_Cycle)}

```

---

### Completed Event Data

```{r Event_Data,echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Missing Pictures**<br>")
# if(nrow(Events_No_Pictures)==0) cat("Every event has pictures taken.<br>") else {
# errorText("Events with no pictures taken:"); NiceTable(Events_No_Pictures)}
# 
# cat("<br>**Missing CWD**<br>")
# if(nrow(Events_No_CWD)==0) cat("Every event has CWD checkboxes checked.<br>") else {
# errorText("Events with unchecked CWD checkboxes:"); NiceTable(Events_No_CWD)}
# 
# cat("<br>**Invasive Early Detection**<br>")
# if(nrow(Events_No_Invasive_Early_Detect)==0) cat("Every event has an appropriate invasive early detection code.<br>") else {
# errorText("Events without an appropriate invasive early detection code:"); NiceTable(Events_No_Invasive_Early_Detect)}
# 
# cat("<br>**Rare Species Detection**<br>")
# if(nrow(Events_No_Rare_Species)==0) cat("Every event has an appropriate rare species detection code.<br>") else {
# errorText("Events without an appropriate rare species detection code:"); NiceTable(Events_No_Rare_Species)}
# 
# cat("<br>**Plot Maintenance**<br>")
# if(nrow(Events_No_Plot_Maint)==0) cat("Every event has an appropriate plot maintenance code.<br>") else {
# errorText("Events without an appropriate plot maintenance code:"); NiceTable(Events_No_Plot_Maint)}

```

---

### Data Processing Level

```{r Event_Data_Processing,echo=FALSE, hold=FALSE, results="asis"}
# cat("<br>**Data Verfication**<br>")
# if(nrow(Events_Not_Verified)==0) cat("All events are verified.<br>") else {
# errorText("Events that are not verified:"); NiceTable(Events_Not_Verified)}
# 
# if(nrow(Events_Bad_Verified_Date)==0) cat("Verified Date is either a date or blank.<br>") else {
# errorText("Events whose verification date is neither a date nor blank"); NiceTable(Events_Bad_Verified_Date)}
# 
# if(nrow(Events_Verified_Mismatch)==0) cat("All verified events have a verified date, and no unverified events have a verified date.<br>") else {
# errorText("Events whose verificaiton code and verification date are inconsistent:"); NiceTable(Events_Verified_Mismatch)}
# 
# if(nrow(Events_Verified_Anachronism)==0) cat("All verified dates are after the event date.<br>") else {
# errorText("Events whose verification date is not after the event date:"); NiceTable(Events_Verified_Anachronism)}
# 
# cat("<br>**Data Certification**<br>")
# if(nrow(Events_Not_Certified)==0) cat("All events are certified.<br>") else {
# errorText("Events that are not certified:"); NiceTable(Events_Not_Certified)}
# 
# if(nrow(Events_Certified_Not_Verified)==0) cat("Every certified event has been verified.<br>") else {
# errorText("Events that are certified but not verified:"); NiceTable(Events_Certified_Not_Verified)}
# 
# if(nrow(Events_Bad_Certified_Date)==0) cat("Certified Date is either a date or blank.<br>") else {
# errorText("Events whose certification date is neither a date nor blank"); NiceTable(Events_Bad_Certified_Date)}
# 
# if(nrow(Events_Certified_Mismatch)==0) cat("All certified events have a certified date, and no uncertified events have a certified date.<br>") else {
# errorText("Events whose certification code and certification date are inconsistent:"); NiceTable(Events_Certified_Mismatch)}
# 
# if(nrow(Events_Certified_Anachronism)==0) cat("All certified dates are after the verification date.<br>") else {
# errorText("Events whose certification date is not after the verification date:"); NiceTable(Events_Certified_Anachronism)}
# 
# cat("<br>**Data Processing**<br>")
# if(nrow(Events_Bad_Data_Processing)==0) cat("All events have data processing levels are recognized and  consistent.<br>") else {
# errorText("Events that have unused or inconsistent data processing levels:"); NiceTable(Events_Bad_Data_Processing)}
# 
# if(nrow(Events_Data_Processing_Anachronism)==0) cat("All data processing dates are on or after the certification date.<br>") else {
# errorText("Events whose data processing date date is before the certification date:"); NiceTable(Events_Data_Processing_Anachronism)}

```


