---
title: "Bird Observation Data QC"
author: "John Paul Schmit"
date: "5/18/2020"
output: html_document
---

```{r Field_Setup, include=F}
TotObs<-nrow(QCBirds) #Total Number of visits checked

# 3.1.0
Birds_Bad_Unit<-QCBirds %>% 
    filter(!Admin_Unit_Code %in% c("ANTI", "CATO", "CHOH", "GWMP", "HAFE", "MANA", "MONO", "NACE", "PRWI", "ROCR", "WOTR")) %>% 
    select(Admin_Unit_Code, Point_Name, EventDate, AOU_Code)
 
#3.2.0
Birds_Missing_Point<-QCBirds %>% 
  filter(is.na(Point_Name) | Point_Name=="" | !Point_Name %in% QCPoints$Point_Name) %>% 
  select(Admin_Unit_Code, Point_Name, EventDate, AOU_Code)

#3.3.0
Birds_No_Date<-QCBirds %>%
  filter(is.na(EventDate) | EventDate==""| !EventDate %in% QCVisits$EventDate)  %>%
  select(Admin_Unit_Code,Point_Name, Year, EventDate, AOU_Code)
 
#3.4.0
Birds_Bad_Year<-QCBirds %>% filter(Year!=year(EventDate)) %>% 
  select(Admin_Unit_Code, Point_Name, EventDate, Year, AOU_Code)

#3.5.0
Birds_Bad_Visit<-QCBirds %>% 
   anti_join(QCVisits %>% select(Point_Name, EventDate, Visit)) %>% 
   select(Admin_Unit_Code, Point_Name, EventDate, Visit, AOU_Code)
 
#3.6.0
Birds_No_AOU<-QCBirds %>% 
   filter(is.na(AOU_Code) | AOU_Code=="" ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code)

Birds_No_Latin<-QCBirds %>% 
   filter(is.na(Scientific_Name) | Scientific_Name=="" ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Scientific_Name)

Birds_No_Common<-QCBirds %>% 
   filter(is.na(Common_Name) | Common_Name=="" ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Common_Name)

Birds_No_Taxon_Code<-QCBirds %>% 
   filter(is.na(NPSTaxonCode) | NPSTaxonCode=="" ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, NPSTaxonCode)

Birds_No_TSN<-QCBirds %>% 
   filter(is.na(AcceptedTSN) | AcceptedTSN=="" ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, AcceptedTSN)

#3.7.0
Birds_Bad_Interval<-QCBirds %>% 
   filter(!(Interval==1 & Interval_Length=="0-2.5 min") &
             !(Interval==2 & Interval_Length=="2.5 - 5 min") &
             !(Interval==3 & Interval_Length=="5 - 7.5 min") &
             !(Interval==4 & Interval_Length=="7.5 - 10 min")) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Interval, Interval_Length)

#3.8.0
Birds_Bad_Method<-QCBirds %>% 
   filter(!(ID_Method_Code=="C" & ID_Method=="Calling") &
             !(ID_Method_Code=="S" & ID_Method=="Singing") &
             !(ID_Method_Code=="V" & ID_Method=="Visualization") ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, ID_Method_Code, ID_Method)

#3.9.0
Birds_Bad_Distance<-QCBirds %>% 
   filter(!(Distance_id==1 & Distance=="<= 50 Meters") &
             !(Distance_id==2 & Distance=="50 - 100 Meters") &
             !(Distance_id==4 & Distance=="<= 25 Meters") &
             !(Distance_id==5 & Distance=="25 - 50 Meters") &
             !(is.na(Distance_id) & Flyover_Observed )) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Distance_id, Distance)

Birds_Anachronoistic_Distance<- QCBirds %>% 
   filter( (Distance_id==1 & Year>2018) |
           (Distance_id==4 & Year<2019) |
           (Distance_id==5 & Year<2019)  ) %>% 
   select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Distance_id, Distance)   

#3.10.0
Birds_Bad_Sex<-QCBirds %>% 
   filter(!(Sex_ID==1 & Sex=="Undetermined") &
          !(Sex_ID==2 & Sex=="Male") &
          !(Sex_ID==3 & Sex =="Female") ) %>% 
    select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Sex_ID, Sex)  


#3.11.0
Birds_Bad_Flyover<-QCBirds %>% 
   filter(!Flyover_Observed %in% c(0,1)) %>% 
    select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Flyover_Observed) 

#3.12.0
Birds_Bad_Three_Min<-QCBirds %>% 
   filter(!Initial_Three_Min_Cnt %in% c(0,1)) %>% 
    select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Initial_Three_Min_Cnt)

#3.13.0
Birds_Bad_Stewardship<-QCBirds %>% 
   filter(!Regional_Stewardship_Status %in% c(0,1)) %>% 
    select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Regional_Stewardship_Status)

#3.14.0
Birds_Bad_Watchlist<-QCBirds %>% 
   filter(!PIF_Watchlist_Status %in% c(0,1)) %>% 
    select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, PIF_Watchlist_Status)

#3.15.0
Birds_Bad_Count<-QCBirds %>% 
   filter(is.na(Bird_Count) | Bird_Count<1) %>% 
    select(Admin_Unit_Code, Point_Name, Year, EventDate, AOU_Code, Bird_Count)

```

#### **Bird Observations Checked:** `r TotObs` ####


### Bird Observation Unit Codes

```{r Bird_Location, echo=FALSE, hold=FALSE, results="asis"}

 cat("<br>**Missing or Incorrect Unit Code**<br>")
 if(nrow(Birds_Bad_Unit)==0) cat("All bird observations have a recoginized unit code.<br>") else {
 errorText("Bird observations without a recognized unit code:"); NiceTable(Birds_Bad_Unit)}

```

---

### Bird Observation Points

```{r Bird_Points, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Point Name**<br>")
if(nrow(Birds_Missing_Point)==0) cat("All bird observations have a point name that we use.<br>") else {
errorText("Bird observations without a point name, or from a point we don't monitor:"); NiceTable(Birds_Missing_Point)}

```


---

### Visit Date

```{r Bird_Date, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Visit Date**<br>")
if(nrow(Visits_No_Date)==0) cat("All bird observations have a valid visit date.<br>") else {
errorText("Birds observatiosn without a valid visit date:"); NiceTable(Birds_No_Date)}

cat("<br>**Year should match Visit Date**<br>")
if(nrow(Birds_Bad_Year)==0) cat("All bird observation years match their event dates.<br>") else {
errorText("There is a mismach between year and event date:"); NiceTable(Birds_Bad_Year)}

```

---

### Visit Number

```{r Birds_visit_mumber, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Incorrect Visit Number**<br>")
if(nrow(Birds_Bad_Visit)==0) cat("All bird observstions have a valid visit number.<br>") else {
errorText("Bird obsservations without a valid visit number or a visit number that does not match the visti data:"); NiceTable(Birds_Bad_Visit)}

```

---

### Bird Identification

```{r Birds_Identification, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing AOU Code**<br>")
if(nrow(Birds_No_AOU)==0) cat("All bird observations have an AOU code.<br>") else {
errorText("Bird observations without an AOU code:"); NiceTable(Birds_No_AOU)}

cat("<br>**Missing Scientific Name**<br>")
if(nrow(Birds_No_Latin)==0) cat("All bird observations have a scientific name.<br>") else {
errorText("Bird observations without a scientific name:"); NiceTable(Birds_No_Latin)}

cat("<br>**Missing Common Name**<br>")
if(nrow(Birds_No_Common)==0) cat("All bird observations have a common name.<br>") else {
errorText("Bird observations without a common name:"); NiceTable(Birds_No_Common)}

cat("<br>**Missing NPS Taxon Code**<br>")
if(nrow(Birds_No_Taxon_Code)==0) cat("All bird observations have an NPS taxon code.<br>") else {
errorText("Bird observations without an NPS taxon code:"); NiceTable(Birds_No_Taxon_Code)}

cat("<br>**Missing Accepted TSN**<br>")
if(nrow(Birds_No_TSN)==0) cat("All bird observations have an accpeted TSN.<br>") else {
  errorText("Bird observations without an accepted TSN:"); NiceTable(Birds_No_TSN)}

```

---

### Interval

```{r Birds_Interval, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Inconsistent Interval and Interval Length**<br>")
if(nrow(Birds_Bad_Interval)==0) cat("All bird observations have consistent intrevals and interval lengths.<br>") else {
errorText("Bird observatrions with inconsistent intervals and interval lengths:"); NiceTable(Birds_Bad_Interval)}

```

---

### ID Method

```{r Birds_Method, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Inconsistent ID Method and Code**<br>")
if(nrow(Birds_Bad_Method)==0) cat("All bird observations have consistent ID Methods and ID Method Codes.<br>") else {
errorText("Bird observatrions with inconsistent ID Methods and ID Method Codes:"); NiceTable(Birds_Bad_Method)}

```

---

### Distance

```{r Birds_Distance, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Inconsistent Distance ID and Distance**<br>")
if(nrow(Birds_Bad_Distance)==0) cat("All bird observations have consistent Distance IDs and Distances.<br>") else {
errorText("Bird observatrions with inconsistent Distance IDs and Distances:"); NiceTable(Birds_Bad_Distance)}

cat("<br>**Anachronistic Distance Bands**<br>")
if(nrow(Birds_Anachronoistic_Distance)==0) cat("All bird observations have Distance IDs and Distances that were in use that year.<br>") else {
errorText("Bird observatrions with Distance IDs and Distances that were not in use in that year:"); NiceTable(Birds_Bad_Distance)}

```


---

### Sex

```{r Birds_Sex, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Inconsistent Sex ID and Sex**<br>")
if(nrow(Birds_Bad_Sex)==0) cat("All bird observations have consistent Sex IDs and Sexes.<br>") else {
errorText("Bird observations with inconsistent Sex IDs and Sexes:"); NiceTable(Birds_Bad_Sex)}

```

---

### Flyovers

```{r Birds_Flyovers, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Invalid Flyover Codes**<br>")
if(nrow(Birds_Bad_Flyover)==0) cat("All bird observations have valid Flyover codes.<br>") else {
errorText("Bird observatrions with invalid flyover codes:"); NiceTable(Birds_Bad_Flyover)}

```

---

### Initial Three Minute Count

```{r Birds_Three_Min, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Invalid Three Minute Count Codes**<br>")
if(nrow(Birds_Bad_Three_Min)==0) cat("All bird observations have valid Initial Three Minute Count codes.<br>") else {
errorText("Bird observations with invalid Three Minue Count Codes:"); NiceTable(Birds_Bad_Three_Min)}

```

---

### Retgional Stewardship Status

```{r Birds_Stewardship, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Invalid Regional Stewardship Status Codes**<br>")
if(nrow(Birds_Bad_Stewardship)==0) cat("All bird observations have valid Regional Stewardship Status codes.<br>") else {
errorText("Bird observations with invalid Regional Stewardship Status codes:"); NiceTable(Birds_Bad_Stewardship)}

```

---

### PIF Watchlist Status

```{r Birds_Watchlist, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Invalid PIF Watchlist Status Codes**<br>")
if(nrow(Birds_Bad_Watchlist)==0) cat("All bird observations have valid PIF Watchlist Status codes.<br>") else {
errorText("Bird observations with invalid PIF Wathclist Status codes:"); NiceTable(Birds_Bad_Watchlist)}

```




---

### Bird Count

```{r Birds_Count, echo=FALSE, hold=FALSE, results="asis"}

cat("<br>**Missing or Invalid Bird Count**<br>")
if(nrow(Birds_Bad_Count)==0) cat("All bird observations have a Bird Count >0.<br>") else {
errorText("Bird observations with a missing or <1 Bird Count:"); NiceTable(Birds_Bad_Count)}

```

